### ISSUE TITLE
light mode contributor 

### ISSUE THREAD

**Issue by TodePond** [TodePond/nDreamBerd#530]
@alifeee might need a light mode version

![Screenshot_20231215-191414](https://github.com/TodePond/nDreamBerd/assets/15892272/ac295804-ce04-4864-96be-bac36e22ca38)

**Comment by alifeee** [comment]
what if I do not want to be percieved by light-mode users

**Comment by TodePond** [comment]
unfortunately the default github pages style is only light mode 

https://www.dreamberd.computer/contributors/

**Comment by alifeee** [comment]
understandable I'll do it
